### PR TITLE
Prevent panic when resizing on linux/vulkan

### PR DESCRIPTION
**Pull request by human9**
Stop part01-resizing from panicking when resizing on Linux, hopefully fixing #1
Although I guess it changes the meaning of the `resizing` variable to mean `remake_swapchain`.

### CODE REVIEW

**Comment by Mistodon** [comment]
Thanks so much for this! Can I ask for a small change though - rather than using `continue` after getting an error on `acquire_image`, can we request the image earlier in the mainloop and recreate the swapchain in the same iteration if needed?

**Comment by human9** [comment]
No worries! I'm just trying to figure out a clean way to do that - as we need to access the swapchain in the first place to call `acquire_image`

**Comment by Mistodon** [comment]
Ahh, I see. In that case, I'm happy to just use `continue` for now. We have to skip rendering anyway if present fails.

**Comment by human9** [comment]
Seems fair!
(Thanks so much for doing this tutorial by the way! I was too afraid to even try gfx-hal until now 😅)

**Comment by Mistodon** [comment]
It is a bit daunting yeah :O part of the reason I wanted to write them. Hopefully the future parts are helpful for you too. Thanks again for the PR - would've taken me a while to fix this myself. :)

**Pull request merged**
